# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_resume_title', models.CharField(max_length=150)),
                ('custom_resume_objective', models.TextField(blank=True)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_resume1.ContactInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_institution', models.CharField(max_length=150)),
                ('education_degree', models.CharField(max_length=100)),
                ('education_dates', models.CharField(max_length=25)),
                ('education_gpa', models.CharField(max_length=4)),
                ('education_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category', models.CharField(max_length=50)),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_organization', models.CharField(max_length=150)),
                ('volunteer_dates', models.CharField(max_length=25)),
                ('volunteer_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place', models.CharField(max_length=150)),
                ('work_dates', models.CharField(max_length=25)),
                ('work_description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='customresume',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_resume1.Education'),
        ),
        migrations.AddField(
            model_name='customresume',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_resume1.Skill'),
        ),
        migrations.AddField(
            model_name='customresume',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_resume1.VolunteerExperience'),
        ),
        migrations.AddField(
            model_name='customresume',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_resume1.WorkExperience'),
        ),
    ]
