# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_resume1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='education_state',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerexperience',
            name='volunteer_city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerexperience',
            name='volunteer_state',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='work_city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='work_state',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
