# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_resume1', '0004_auto_20171222_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='customresume',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='master_resume1.Profile'),
            preserve_default=False,
        ),
    ]
